### ISSUE TITLE
[WORK🛠️] 유저 - 회원 탈퇴

### ISSUE THREAD

**Issue by kjy-asl** [Gam-develop/gam-server#127]
## 🧐 설명!
- 회원 탈퇴 기능을 개발합니다.
 

## ✔ 해야할 일! 
- [ ] 회원 탈퇴 여부 status 필드 생성
- [ ] 스케줄러를 통해 탈퇴 회원 삭제

**Comment by GaHee99** [comment]
이슈 해결
