### ISSUE TITLE
[MAGAZINE 🛠] 매거진 - 발견, 세부, 스크랩 뷰, 스크랩

### ISSUE THREAD

**Issue by dragontaek-lee** [Gam-develop/gam-server#38]
## 🧐 설명!
- 매거진 관련 API 개발

## ✔ 해야할 일! 
- 수행해야 하는 순서대로 특정 작업을 포함합니다. 
- [ ] 발견
- [ ] 세부
- [ ] 스크랩 뷰
- [ ] 스크랩

**Comment by GaHee99** [comment]
merged in develop
