### ISSUE TITLE
[WORK🛠]  버전 정보, 서비스 소개 - 약관 - 개인정보 처리 방침 url, 발견 무한 매거진

### ISSUE THREAD

**Issue by dragontaek-lee** [Gam-develop/gam-server#70]
## 🧐 설명!
- 현재 버전 정보 주기
- 서비스 소개, 약관, 개인정보 처리 방침 url 
- 발견 무한 매거진 제공
 

## ✔ 해야할 일! 
- 수행해야 하는 순서대로 특정 작업을 포함합니다. 
- [x] 현재 버전 정보
- [x] 개인 정보 처리 방침 url
- [x] 발견 무한 매거진 제공

**Comment by GaHee99** [comment]
merged in develop
